version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      # - 기타_환경변수=값 (예: LLM_API_KEY=...)
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped

volumes:
  uploads:
    driver: local 